name: Build MIA Trigger VST3

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2022
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
