name: Build MIA Trigger VST3

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: 
      windows-2022
      cmake -S . -B build -A x64
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
